<?php

return [
    [
        'mod' => 'Vanilla Survival',
        'categories' =>[
            'Abbonamento' => [
                [
                    'id' => '1',
                    'name' => 'Abbonamento +',
                    'fullprice' => '11.00',
                    'currentprice' => '9.35',
                    'currency' => 'EUR',
                    'image' => 'img/store/abbonamento_1_vs.png',
                ],
                [
                    'id' => '2',
                    'name' => 'Abbonamento ++',
                    'fullprice' => '20.00',
                    'currentprice' => '17.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/abbonamento_2_vs.png',
                ],
            ],
            'Vip' => [
                [
                    'id' => '3',
                    'name' => 'Prova Vip 48 Ore',
                    'fullprice' => '',
                    'currentprice' => '0.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/vip_48h_vs.png',
                ],
                [
                    'id' => '4',
                    'name' => 'Recluta',
                    'fullprice' => '12.00',
                    'currentprice' => '10.20',
                    'currency' => 'EUR',
                    'image' => 'img/store/vip_recluta_vs.png',
                ],
                [
                    'id' => '5',
                    'name' => 'Automa',
                    'fullprice' => '27.00',
                    'currentprice' => '22.95',
                    'currency' => 'EUR',
                    'image' => 'img/store/vip_automa_vs.png',
                ],
                [
                    'id' => '6',
                    'name' => 'Cyborg',
                    'fullprice' => '59.00',
                    'currentprice' => '50.15',
                    'currency' => 'EUR',
                    'image' => 'img/store/vip_cyborg_vs.png',
                ],
                [
                    'id' => '7',
                    'name' => 'Terminator',
                    'fullprice' => '108.00',
                    'currentprice' => '91.80',
                    'currency' => 'EUR',
                    'image' => 'img/store/vip_terminator_vs.png',
                ],
                [
                    'id' => '8',
                    'name' => 'Kronos',
                    'fullprice' => '210.00',
                    'currentprice' => '178.50',
                    'currency' => 'EUR',
                    'image' => 'img/store/vip_kronos_vs.png',
                ],
                [
                    'id' => '9',
                    'name' => 'MultiVerso',
                    'fullprice' => '300.00',
                    'currentprice' => '255.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/vip_vs_multiverso.png',
                ],
            ],
            'Vip Upgrade' => [
                [
                    'id' => '10',
                    'name' => 'Recluta >> Automa',
                    'fullprice' => '15.00',
                    'currentprice' => '12.75',
                    'currency' => 'EUR',
                    'image' => 'img/store/upgrade_recluta_vs.png',
                ],
                [
                    'id' => '11',
                    'name' => 'Automa >> Cyborg',
                    'fullprice' => '32.00',
                    'currentprice' => '27.20',
                    'currency' => 'EUR',
                    'image' => 'img/store/upgrade_automa_vs.png',
                ],
                [
                    'id' => '12',
                    'name' => 'Cyborg >> Terminator',
                    'fullprice' => '49.00',
                    'currentprice' => '41.65',
                    'currency' => 'EUR',
                    'image' => 'img/store/upgrade_cyborg_vs.png',
                ],
                [
                    'id' => '13',
                    'name' => 'Terminator >> Kronos',
                    'fullprice' => '102.00',
                    'currentprice' => '86.70',
                    'currency' => 'EUR',
                    'image' => 'img/store/upgrade_terminator_vs.png',
                ],
                [
                    'id' => '14',
                    'name' => 'Kronos >> Multiverso',
                    'fullprice' => '90.00',
                    'currentprice' => '76.50',
                    'currency' => 'EUR',
                    'image' => 'img/store/upgrade_kronos_vs.png',
                ],
            ]
        ]
    ],
    [
        'mod' => 'Towny',
        'categories' => [
            'Vip' => [
                [
                    'id' => '15',
                    'name' => 'Vip Discepolo',
                    'fullprice' => '',
                    'currentprice' => '12.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/vip_discepolo_t.png',
                ],
                [
                    'id' => '16',
                    'name' => 'Vip Evocatore',
                    'fullprice' => '',
                    'currentprice' => '24.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/vip_evocatore_t.png',
                ],
                [
                    'id' => '17',
                    'name' => 'Vip Leviatano',
                    'fullprice' => '',
                    'currentprice' => '54.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/vip_leviatano_t.png',
                ],
                [
                    'id' => '18',
                    'name' => 'Vip Alpha',
                    'fullprice' => '',
                    'currentprice' => '84.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/vip_alpha_t.png',
                ],
                [
                    'id' => '19',
                    'name' => 'Vip Titano',
                    'fullprice' => '',
                    'currentprice' => '129.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/vip_titano_t.png',
                ],
            ],
            'Vip Upgrade' => [
                [
                    'id' => '20',
                    'name' => 'Discepolo >> Evocatore',
                    'fullprice' => '',
                    'currentprice' => '12.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/vip_discepolo_t.png',
                ],
                [
                    'id' => '21',
                    'name' => 'Evocatore >> Leviatano',
                    'fullprice' => '',
                    'currentprice' => '30.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/vip_evocatore_t.png',
                ],
                [
                    'id' => '22',
                    'name' => 'Leviatano >> Alpha',
                    'fullprice' => '',
                    'currentprice' => '30.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/vip_leviatano_t.png',
                ],
                [
                    'id' => '23',
                    'name' => 'Alpha >> Titano',
                    'fullprice' => '',
                    'currentprice' => '38.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/vip_alpha_t.png',
                ],
            ],
            'Gadget' => [
                [
                    'id' => '24',
                    'name' => 'Towny Fly',
                    'fullprice' => '',
                    'currentprice' => '18.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/fly_1_t.png',
                ],
                [
                    'id' => '25',
                    'name' => 'Upgrade Towny Fly',
                    'fullprice' => '',
                    'currentprice' => '18.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/fly_2_t.png',
                ],
                [
                    'id' => '26',
                    'name' => 'Enderchest Alpha',
                    'fullprice' => '',
                    'currentprice' => '7.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/ec_1_t.png',
                ],
                [
                    'id' => '27',
                    'name' => 'Upgrade Alpha',
                    'fullprice' => '',
                    'currentprice' => '6.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/ec_2_t.png',
                ],
                [
                    'id' => '28',
                    'name' => 'Enderchest Beta',
                    'fullprice' => '',
                    'currentprice' => '7.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/ec_1_t.png',
                ],
                [
                    'id' => '29',
                    'name' => 'Upgrade Beta',
                    'fullprice' => '',
                    'currentprice' => '6.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/ec_2_t.png',
                ],
                [
                    'id' => '30',
                    'name' => 'Enderchest Gamma',
                    'fullprice' => '',
                    'currentprice' => '7.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/ec_1_t.png',
                ],
                [
                    'id' => '31',
                    'name' => 'Upgrade Gamma',
                    'fullprice' => '',
                    'currentprice' => '6.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/ec_2_t.png',
                ],
                [
                    'id' => '32',
                    'name' => 'Mistery Key',
                    'fullprice' => '',
                    'currentprice' => '5.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/mistery_key_t.png',
                ],
            ],
            'Offerte Speciali' => [
                [
                    'id' => '33',
                    'name' => 'Discepolo dell\'End',
                    'fullprice' => '',
                    'currentprice' => '18.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/speciali_t.png',
                ],
                [
                    'id' => '34',
                    'name' => 'Evocatore dell\'End',
                    'fullprice' => '',
                    'currentprice' => '33.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/speciali_t.png',
                ],
                [
                    'id' => '35',
                    'name' => 'Leviatano dell\'End',
                    'fullprice' => '',
                    'currentprice' => '61.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/speciali_t.png',
                ],
                [
                    'id' => '36',
                    'name' => 'Alpha dell\'End',
                    'fullprice' => '',
                    'currentprice' => '94.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/speciali_t.png',
                ],
                [
                    'id' => '37',
                    'name' => 'Bundle Enderches',
                    'fullprice' => '',
                    'currentprice' => '24.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/speciali_t.png',
                ],
            ]
        ]
    ],
    [
        'mod' => 'SkyPvp',
        'categories' => [
            'dCoin' => [
                [
                    'id' => '38',
                    'name' => '100 dCoin',
                    'fullprice' => '',
                    'currentprice' => '12.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/speciali_t.png',
                ],
                [
                    'id' => '39',
                    'name' => '250 dCoin',
                    'fullprice' => '',
                    'currentprice' => '25.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/speciali_t.png',
                ],
                [
                    'id' => '40',
                    'name' => '450 dCoin',
                    'fullprice' => '',
                    'currentprice' => '42.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/speciali_t.png',
                ],
                [
                    'id' => '41',
                    'name' => '950 dCoin',
                    'fullprice' => '',
                    'currentprice' => '80.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/speciali_t.png',
                ],
            ]
        ]
    ],
    [
        'mod' => 'Globale',
        'categories' => [
            'Vip' => [
                [
                    'id' => '42',
                    'name' => 'MVP',
                    'fullprice' => '',
                    'currentprice' => '47.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/mvp_1.png',
                ],
                [
                    'id' => '43',
                    'name' => 'MVP+',
                    'fullprice' => '',
                    'currentprice' => '410.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/mvp_2.png',
                ],
            ],
            'Pass' =>[
                [
                    'id' => '44',
                    'name' => 'Priorità Coda (One)',
                    'fullprice' => '',
                    'currentprice' => '3.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/pass_1.png',
                ],
                [
                    'id' => '45',
                    'name' => 'Priorità Coda (Life)',
                    'fullprice' => '',
                    'currentprice' => '8.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/pass_2.png',
                ],
            ],
            'TeamSpeak' => [
                [
                    'id' => '46',
                    'name' => 'Boost',
                    'fullprice' => '',
                    'currentprice' => '35.00',
                    'currency' => 'EUR',
                    'image' => 'img/store/boost_ts.jpg',
                ],
            ],
        ]
    ]
];

